### PR TITLE
update tray icons

### PR DESCRIPTION
**Pull request by MeijeSibbel**
Update the tray icons to newer versions. If everything is ok please merge.

### CODE REVIEW

**Comment by MeijeSibbel** [comment]
let me also add the windows 7 icons, sec.

**Comment by MeijeSibbel** [comment]
ups, forgot the pause one. sec

**Comment by MeijeSibbel** [comment]
@jkawamoto , i think i am done. In the windows-7 icons there weren't any error, warning and pause icons btw. If it looks ok please merge.

**Comment by jkawamoto** [comment]
Thanks!

**Pull request merged**
